// Code generated by modelgen; DO NOT EDIT.

package catalog

import oasis "github.com/nevindra/oasis"

// staticModels is the pre-compiled model registry.
// Updated by: go generate ./provider/catalog/...
// Sources: OpenRouter API + models.dev
var staticModels = []oasis.ModelInfo{
	// --- OpenAI ---
	{ID: "gpt-4o", Provider: "openai", DisplayName: "GPT-4o", InputContext: 128000, OutputContext: 16384, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 2.50, OutputPerMillion: 10.00}},
	{ID: "gpt-4o-mini", Provider: "openai", DisplayName: "GPT-4o Mini", InputContext: 128000, OutputContext: 16384, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.15, OutputPerMillion: 0.60}},
	{ID: "gpt-4.1", Provider: "openai", DisplayName: "GPT-4.1", InputContext: 1047576, OutputContext: 32768, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 2.00, OutputPerMillion: 8.00}},
	{ID: "gpt-4.1-mini", Provider: "openai", DisplayName: "GPT-4.1 Mini", InputContext: 1047576, OutputContext: 32768, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.40, OutputPerMillion: 1.60}},
	{ID: "gpt-4.1-nano", Provider: "openai", DisplayName: "GPT-4.1 Nano", InputContext: 1047576, OutputContext: 32768, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.10, OutputPerMillion: 0.40}},
	{ID: "o3-mini", Provider: "openai", DisplayName: "o3 Mini", InputContext: 200000, OutputContext: 100000, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 1.10, OutputPerMillion: 4.40}},

	// --- Gemini ---
	{ID: "gemini-2.5-flash", Provider: "gemini", DisplayName: "Gemini 2.5 Flash", InputContext: 1048576, OutputContext: 65536, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.15, OutputPerMillion: 0.60}},
	{ID: "gemini-2.5-pro", Provider: "gemini", DisplayName: "Gemini 2.5 Pro", InputContext: 1048576, OutputContext: 65536, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 1.25, OutputPerMillion: 10.00}},
	{ID: "gemini-2.0-flash", Provider: "gemini", DisplayName: "Gemini 2.0 Flash", InputContext: 1048576, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.10, OutputPerMillion: 0.40}},
	{ID: "gemini-2.0-flash-lite", Provider: "gemini", DisplayName: "Gemini 2.0 Flash Lite", InputContext: 1048576, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.0, OutputPerMillion: 0.0}},

	// --- DeepSeek ---
	{ID: "deepseek-chat", Provider: "deepseek", DisplayName: "DeepSeek V3", InputContext: 131072, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.27, OutputPerMillion: 1.10}},
	{ID: "deepseek-reasoner", Provider: "deepseek", DisplayName: "DeepSeek R1", InputContext: 131072, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.55, OutputPerMillion: 2.19}},

	// --- Groq ---
	{ID: "llama-3.3-70b-versatile", Provider: "groq", DisplayName: "Llama 3.3 70B", InputContext: 131072, OutputContext: 32768, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.59, OutputPerMillion: 0.79}},
	{ID: "llama-3.1-8b-instant", Provider: "groq", DisplayName: "Llama 3.1 8B", InputContext: 131072, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.05, OutputPerMillion: 0.08}},

	// --- Mistral ---
	{ID: "mistral-large-latest", Provider: "mistral", DisplayName: "Mistral Large", InputContext: 131072, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 2.00, OutputPerMillion: 6.00}},
	{ID: "mistral-small-latest", Provider: "mistral", DisplayName: "Mistral Small", InputContext: 131072, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.10, OutputPerMillion: 0.30}},

	// --- Qwen ---
	{ID: "qwen-turbo", Provider: "qwen", DisplayName: "Qwen Turbo", InputContext: 131072, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}},
	{ID: "qwen-plus", Provider: "qwen", DisplayName: "Qwen Plus", InputContext: 131072, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}},
	{ID: "qwen-max", Provider: "qwen", DisplayName: "Qwen Max", InputContext: 131072, OutputContext: 8192, Capabilities: oasis.ModelCapabilities{Chat: true, Vision: true, ToolUse: true}},

	// --- Together ---
	{ID: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo", Provider: "together", DisplayName: "Llama 3.1 70B Instruct Turbo", InputContext: 131072, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.88, OutputPerMillion: 0.88}},
	{ID: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo", Provider: "together", DisplayName: "Llama 3.1 8B Instruct Turbo", InputContext: 131072, Capabilities: oasis.ModelCapabilities{Chat: true, ToolUse: true}, Pricing: &oasis.ModelPricing{InputPerMillion: 0.18, OutputPerMillion: 0.18}},
}
