package sandbox

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
	"sync/atomic"
	"testing"

	oasis "github.com/nevindra/oasis/core"
)

// commitSandbox is a recordingSandbox that can run a command. shell,
// execute_code and mcp_call apply a canned mutation of the guest filesystem —
// which is all "a CLI toolchain wrote a file" means to this package — and the
// glob/download counters record what the change detector cost.
type commitSandbox struct {
	*recordingSandbox
	run       func(s *recordingSandbox)
	globs     atomic.Int64
	downloads atomic.Int64
}

func newCommitSandbox(run func(s *recordingSandbox)) *commitSandbox {
	return &commitSandbox{recordingSandbox: newRecordingSandbox(), run: run}
}

func (s *commitSandbox) Shell(ctx context.Context, req ShellRequest) (ShellResult, error) {
	if s.run != nil {
		s.run(s.recordingSandbox)
	}
	return ShellResult{Output: "ran " + req.Command}, nil
}

func (s *commitSandbox) ExecCode(ctx context.Context, req CodeRequest) (CodeResult, error) {
	if s.run != nil {
		s.run(s.recordingSandbox)
	}
	return CodeResult{Status: "ok", Stdout: "done"}, nil
}

func (s *commitSandbox) MCPCall(ctx context.Context, req MCPRequest) (MCPResult, error) {
	if s.run != nil {
		s.run(s.recordingSandbox)
	}
	return MCPResult{Content: "built"}, nil
}

func (s *commitSandbox) GlobFiles(ctx context.Context, req GlobRequest) (GlobResult, error) {
	s.globs.Add(1)
	return s.recordingSandbox.GlobFiles(ctx, req)
}

func (s *commitSandbox) DownloadFile(ctx context.Context, path string) (io.ReadCloser, error) {
	s.downloads.Add(1)
	return s.recordingSandbox.DownloadFile(ctx, path)
}

// writeGuestFile is what a command does from this package's point of view.
func writeGuestFile(s *recordingSandbox, path, content string) {
	if err := s.WriteFile(context.Background(), WriteFileRequest{Path: path, Content: content}); err != nil {
		panic(err)
	}
}

func runTool(t *testing.T, tools []oasis.AnyTool, name, args string) oasis.ToolResult {
	t.Helper()
	tool := findToolByName(tools, name)
	if tool == nil {
		t.Fatalf("%s tool not registered", name)
	}
	res, err := tool.ExecuteRaw(context.Background(), json.RawMessage(args))
	if err != nil {
		t.Fatalf("%s returned a transport error: %v", name, err)
	}
	return res
}

func workspaceSpec(backend FilesystemMount, exclude ...string) []MountSpec {
	return []MountSpec{{
		Path:            "/workspace",
		Backend:         backend,
		Mode:            MountReadWrite,
		PrefetchOnStart: true,
		FlushOnClose:    true,
		Exclude:         exclude,
	}}
}

// ── the point of the ticket ──

func TestShellWriteReachesBackendBeforeTheNextToolCall(t *testing.T) {
	mount := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/report.md", "# generated by typst")
	})
	manifest := NewManifest()
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewFullScanDetector()))

	res := runTool(t, tools, "shell", `{"command":"typst compile report.typ"}`)
	if res.Error != "" {
		t.Fatalf("shell reported an error: %q", res.Error)
	}
	if got := decodeContent(t, res); got != "ran typst compile report.typ" {
		t.Errorf("tool result = %q; the commit must not change what the model sees on success", got)
	}

	// The assertion the PRD makes: durable before the next tool call, not at
	// end of turn. No FlushMounts anywhere in this test.
	if got := string(mount.entries["report.md"].data); got != "# generated by typst" {
		t.Fatalf("backend report.md = %q, want the shell-written content", got)
	}
	if len(mount.commits) != 1 {
		t.Fatalf("backend saw %d commits, want 1", len(mount.commits))
	}
	if got := mount.commits[0][0].Expect; got != ExpectAbsent {
		t.Errorf("precondition = %v, want ExpectAbsent for a file the framework knows was not in the prefetched backend", got)
	}
	if got := mount.commits[0][0].MimeType; got == "" {
		t.Error("the change carried no MimeType; the backend has nothing to serve the file as")
	}
	if ver, ok := manifest.Version("/workspace", "report.md"); !ok || ver == "" {
		t.Error("manifest did not record the version the commit returned; the next commit would assert a stale precondition")
	}
}

func TestSecondWriteCommitsAgainstTheVersionTheFirstReturned(t *testing.T) {
	mount := newTxFakeMount()
	body := "v1 content"
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/report.md", body)
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "shell", `{"command":"first"}`)
	body = "v2 content"
	runTool(t, tools, "shell", `{"command":"second"}`)

	if len(mount.commits) != 2 {
		t.Fatalf("backend saw %d commits, want 2", len(mount.commits))
	}
	second := mount.commits[1][0]
	if second.Expect != ExpectVersion {
		t.Errorf("second commit precondition = %v, want ExpectVersion once the key is tracked", second.Expect)
	}
	if second.Have != "v1" {
		t.Errorf("second commit asserted %q, want the version the first commit returned", second.Have)
	}
	if got := string(mount.entries["report.md"].data); got != "v2 content" {
		t.Errorf("backend report.md = %q, want the second write", got)
	}
}

func TestUnchangedWorkspaceCommitsNothing(t *testing.T) {
	mount := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/report.md", "same bytes every time")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "shell", `{"command":"write"}`)
	runTool(t, tools, "shell", `{"command":"write the same thing"}`)
	runTool(t, tools, "shell", `{"command":"and again"}`)

	if len(mount.commits) != 1 {
		t.Fatalf("backend saw %d commits, want 1 — rewriting identical bytes is not a change", len(mount.commits))
	}
}

// ── off is off ──

func TestToolCallCommitsAreOffByDefault(t *testing.T) {
	mount := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/report.md", "written by shell")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()))

	res := runTool(t, tools, "shell", `{"command":"typst compile report.typ"}`)

	// Same result, and not one extra call into the guest or the backend.
	bare := runTool(t, Tools(newCommitSandbox(nil)), "shell", `{"command":"typst compile report.typ"}`)
	if decodeContent(t, res) != decodeContent(t, bare) || res.Error != bare.Error {
		t.Errorf("result with mounts = %+v, without = %+v; the option being unset must change nothing", res, bare)
	}
	if len(mount.commits) != 0 || mount.stages != 0 {
		t.Errorf("backend saw %d commits and %d stages with the option unset, want 0 and 0", len(mount.commits), mount.stages)
	}
	if len(mount.entries) != 0 {
		t.Errorf("backend holds %d entries; without the option a shell write waits for the close-time flush", len(mount.entries))
	}
	if g, d := sb.globs.Load(), sb.downloads.Load(); g != 0 || d != 0 {
		t.Errorf("guest saw %d globs and %d downloads with the option unset, want 0 and 0 — detection must not run at all", g, d)
	}
}

func TestNonTransactionalBackendIsNeverScanned(t *testing.T) {
	mount := &countingMount{fakeMount: newFakeMount()}
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/report.md", "written by shell")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "shell", `{"command":"write"}`)

	if got := mount.puts.Load(); got != 0 {
		t.Errorf("plain backend saw %d Puts from the commit path, want 0 — it keeps prefetch/flush behaviour", got)
	}
	if g, d := sb.globs.Load(), sb.downloads.Load(); g != 0 || d != 0 {
		t.Errorf("guest saw %d globs and %d downloads for a backend that cannot commit, want 0 and 0", g, d)
	}
}

func TestReadOnlyMountIsNeverScanned(t *testing.T) {
	mount := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/reference/scratch.md", "local only")
	})
	specs := []MountSpec{{Path: "/reference", Backend: mount, Mode: MountReadOnly, PrefetchOnStart: true}}
	tools := Tools(sb, WithMounts(specs, NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "shell", `{"command":"write"}`)

	if len(mount.commits) != 0 {
		t.Errorf("read-only mount received %d commits, want 0", len(mount.commits))
	}
	if g := sb.globs.Load(); g != 0 {
		t.Errorf("read-only mount was scanned %d times, want 0", g)
	}
}

// ── filters and ownership ──

func TestExcludedPathsAreNeitherFetchedNorCommitted(t *testing.T) {
	mount := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/report.md", "keep me")
		writeGuestFile(s, "/workspace/report.md.tmp", "typst scratch")
		writeGuestFile(s, "/workspace/.cache/blob", "cache junk")
	})
	specs := workspaceSpec(mount, "*.tmp", ".cache/*")
	tools := Tools(sb, WithMounts(specs, NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "shell", `{"command":"typst compile"}`)

	if _, ok := mount.entries["report.md.tmp"]; ok {
		t.Error("an excluded path was committed")
	}
	if _, ok := mount.entries[".cache/blob"]; ok {
		t.Error("an excluded path was committed")
	}
	if string(mount.entries["report.md"].data) != "keep me" {
		t.Error("the included file was not committed")
	}
	// The filter belongs inside the scan, not after it: an excluded file must
	// not cost a transfer either.
	if got := sb.downloads.Load(); got != 1 {
		t.Errorf("guest served %d downloads, want 1 — excluded files must not be read", got)
	}
}

func TestNestedMountFilesGoToTheNestedBackend(t *testing.T) {
	workspace := newTxFakeMount()
	inputs := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/summary.md", "summary")
		writeGuestFile(s, "/workspace/inputs/report.xlsx", "EDITED BY OPENPYXL")
	})
	tools := Tools(sb, WithMounts(athenaSpecs(workspace, inputs), NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "execute_code", `{"code":"import openpyxl"}`)

	if _, ok := workspace.entries["inputs/report.xlsx"]; ok {
		t.Error("the parent backend received a key owned by the nested mount — §1.2's duplicate, one layer earlier")
	}
	if got := string(inputs.entries["report.xlsx"].data); got != "EDITED BY OPENPYXL" {
		t.Errorf("nested backend report.xlsx = %q, want the edit", got)
	}
	if got := string(workspace.entries["summary.md"].data); got != "summary" {
		t.Errorf("parent backend summary.md = %q, want the file it does own", got)
	}
	if len(workspace.commits) != 1 || len(workspace.commits[0]) != 1 {
		t.Errorf("parent commits = %v, want exactly one change", workspace.commits)
	}
	// The nested mount is never prefetched (read-through view), so the
	// framework has never read that backend and cannot claim to know what is
	// under the key.
	if got := inputs.commits[0][0].Expect; got != ExpectAny {
		t.Errorf("nested mount precondition = %v, want ExpectAny on a mount that was never prefetched", got)
	}
}

// ── no double write with Layer 2 ──

func TestLayer2WritesAreNotCommittedTwice(t *testing.T) {
	mount := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {}) // the shell call writes nothing
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "file_write", `{"path":"/workspace/notes.md","content":"from file_write"}`)
	if got := mount.entries["notes.md"].version; got != "v1" {
		t.Fatalf("notes.md version after file_write = %q, want v1", got)
	}

	runTool(t, tools, "shell", `{"command":"ls"}`)

	if len(mount.commits) != 0 {
		t.Errorf("the commit path re-published a Layer 2 write: %v", mount.commits)
	}
	if got := mount.entries["notes.md"].version; got != "v1" {
		t.Errorf("notes.md version = %q, want v1 — the same bytes must not land twice under two versions", got)
	}
}

func TestLayer2WriteOverACommittedFileStillDoesNotDoubleWrite(t *testing.T) {
	mount := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/notes.md", "from shell")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "shell", `{"command":"write"}`)
	sb.run = nil // the next shell call writes nothing
	res := runTool(t, tools, "file_edit", `{"path":"/workspace/notes.md","old_string":"shell","new_string":"file_edit"}`)
	if res.Error != "" {
		t.Fatalf("file_edit: %s", res.Error)
	}
	verAfterEdit := mount.entries["notes.md"].version

	runTool(t, tools, "shell", `{"command":"ls"}`)

	if got := mount.entries["notes.md"].version; got != verAfterEdit {
		t.Errorf("notes.md version = %q, want %q — the sweep re-published Layer 2's edit", got, verAfterEdit)
	}
	if got := string(mount.entries["notes.md"].data); got != "from file_edit" {
		t.Errorf("notes.md = %q, want the edited content", got)
	}
}

func TestConcurrentToolCallsDoNotRaceEachOtherIntoAConflict(t *testing.T) {
	mount := newTxFakeMount()
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/a.md", "written once")
		writeGuestFile(s, "/workspace/b.md", "written once")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))

	results := make(chan oasis.ToolResult, 2)
	go func() { results <- runToolAsync(tools, "shell", `{"command":"build"}`) }()
	go func() { results <- runToolAsync(tools, "execute_code", `{"code":"build()"}`) }()
	for range 2 {
		res := <-results
		if strings.Contains(decodeContent(t, res), "workspace commit failed") {
			t.Errorf("parallel tool calls conflicted with each other: %q", decodeContent(t, res))
		}
	}

	for _, key := range []string{"a.md", "b.md"} {
		if got := mount.entries[key].version; got != "v1" {
			t.Errorf("%s version = %q, want v1 — two sweeps committed the same bytes twice", key, got)
		}
	}
}

// runToolAsync is runTool without the *testing.T, for use off the test
// goroutine.
func runToolAsync(tools []oasis.AnyTool, name, args string) oasis.ToolResult {
	tool := findToolByName(tools, name)
	res, err := tool.ExecuteRaw(context.Background(), json.RawMessage(args))
	if err != nil {
		return oasis.ToolResult{Error: err.Error()}
	}
	return res
}

// ── a rejected commit ──

func TestRejectedCommitNotesTheResultAndRetriesNextCall(t *testing.T) {
	mount := newTxFakeMount()
	mount.seed("doc.md", "theirs", "v2") // a second writer moved it since prefetch

	manifest := NewManifest()
	manifest.Record("/workspace", "doc.md", MountEntry{Key: "doc.md", Size: int64(len("prefetched")), Version: "v1"})

	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/doc.md", "mine")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewFullScanDetector()))

	res := runTool(t, tools, "shell", `{"command":"edit doc.md"}`)

	if res.Error != "" {
		t.Errorf("a failed commit turned a successful shell call into an error: %q", res.Error)
	}
	if !strings.Contains(decodeContent(t, res), "ran edit doc.md") {
		t.Errorf("the tool's own output was lost: %q", decodeContent(t, res))
	}
	if !strings.Contains(decodeContent(t, res), "workspace commit failed") {
		t.Errorf("the failure was not surfaced at all: %q", decodeContent(t, res))
	}
	if got := string(mount.entries["doc.md"].data); got != "theirs" {
		t.Errorf("backend doc.md = %q, want the other writer's content untouched", got)
	}

	// The rejection taught the framework the version it was missing, and the
	// framework kept it. Asserting v1 again would be asserting something it now
	// knows to be false, and the backend would reject it for the same reason
	// forever. See adoptRejectedVersions.
	if ver, _ := manifest.Version("/workspace", "doc.md"); ver != "v2" {
		t.Errorf("manifest version = %q after a rejected commit, want v2 — the version the rejection reported", ver)
	}

	// PRD success criterion 5, end to end: the second writer is rejected, and
	// then retries **successfully**, with no help from the test. Before
	// adoptRejectedVersions this test had to hand the manifest the new version
	// itself, which is precisely what made the criterion unmet — the loop could
	// not close without something outside the framework closing it.
	//
	// The change is still pending, too: a rejected commit is not recorded as
	// progress, so the same local file is committed again rather than written
	// off as already published.
	runTool(t, tools, "shell", `{"command":"try again"}`)
	if got := string(mount.entries["doc.md"].data); got != "mine" {
		t.Fatalf("backend doc.md = %q after the retry, want the local content — the retry must succeed on its own", got)
	}
	if len(mount.commits) != 2 {
		t.Errorf("backend saw %d commit attempts, want 2", len(mount.commits))
	}
}

// The other two things a rejection can report, and why each needs its own
// answer rather than the CHANGED one.
func TestRejectionOfADeletedKeyLetsTheRetryRecreateIt(t *testing.T) {
	mount := newTxFakeMount() // backend holds nothing
	manifest := NewManifest()
	manifest.Record("/workspace", "doc.md", MountEntry{Key: "doc.md", Size: 6, Version: "v1"})

	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/doc.md", "mine")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewStatHashDetector()))

	runTool(t, tools, "shell", `{"command":"edit"}`)

	// Asserting a version of a file that no longer exists can never succeed.
	// Forgetting the key makes the next attempt claim the name is free, which
	// is now the truth.
	if _, tracked := manifest.Version("/workspace", "doc.md"); tracked {
		t.Error("manifest still tracks a key the backend reported as deleted; the retry would assert a dead version")
	}

	runTool(t, tools, "shell", `{"command":"try again"}`)
	if got := string(mount.entries["doc.md"].data); got != "mine" {
		t.Fatalf("backend doc.md = %q after the retry, want it recreated", got)
	}
}

// The mount was prefetched and this key was not in it, so the framework claims
// the name is free. Another writer took it in the meantime.
func TestRejectionOfATakenNameAdoptsTheReportedVersion(t *testing.T) {
	mount := newTxFakeMount()
	mount.seed("new.md", "theirs", "v7")
	manifest := NewManifest()

	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/new.md", "mine")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewStatHashDetector()))

	runTool(t, tools, "shell", `{"command":"edit"}`)

	if ver, _ := manifest.Version("/workspace", "new.md"); ver != "v7" {
		t.Fatalf("manifest version = %q, want v7: without a version this key can never be written", ver)
	}
	runTool(t, tools, "shell", `{"command":"try again"}`)
	if got := string(mount.entries["new.md"].data); got != "mine" {
		t.Fatalf("backend new.md = %q after the retry, want the retry to have landed", got)
	}
}

// mumblingMount rejects an ExpectAbsent claim without naming the version it
// actually holds — permitted by KeyConflict.Want, whose doc says it may be
// empty "when the backend cannot report a version for the key". This is the
// only case where the conflict payload alone cannot close the loop, and the
// only case that costs an extra round trip.
type mumblingMount struct {
	*txFakeMount
	stats atomic.Int64
}

func (m *mumblingMount) Commit(ctx context.Context, changes []MountChange) (CommitResult, error) {
	res, err := m.txFakeMount.Commit(ctx, changes)
	var conflict *CommitConflictError
	if errors.As(err, &conflict) {
		for i := range conflict.Conflicts {
			conflict.Conflicts[i].Want = ""
		}
	}
	return res, err
}

func (m *mumblingMount) Stat(ctx context.Context, key string) (MountEntry, error) {
	m.stats.Add(1)
	return m.txFakeMount.Stat(ctx, key)
}

func TestRejectionWithoutAVersionAsksTheBackendForOne(t *testing.T) {
	mount := &mumblingMount{txFakeMount: newTxFakeMount()}
	mount.seed("new.md", "theirs", "v7")
	manifest := NewManifest()

	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/new.md", "mine")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewStatHashDetector()))

	runTool(t, tools, "shell", `{"command":"edit"}`)

	if n := mount.stats.Load(); n != 1 {
		t.Errorf("Stat called %d times, want 1: a rejection that names no version has no other way to learn one", n)
	}
	if ver, _ := manifest.Version("/workspace", "new.md"); ver != "v7" {
		t.Fatalf("manifest version = %q, want v7 read back from the backend", ver)
	}
	runTool(t, tools, "shell", `{"command":"try again"}`)
	if got := string(mount.entries["new.md"].data); got != "mine" {
		t.Fatalf("backend new.md = %q after the retry, want the retry to have landed", got)
	}
}

func TestAdoptingAVersionStillCatchesAThirdWriter(t *testing.T) {
	// The protection adoptRejectedVersions gives up is that the model is
	// trusted to have read what it was shown. The protection it keeps is this
	// one, and it is the one that matters: a writer landing between the
	// rejection and the retry is still caught.
	mount := newTxFakeMount()
	mount.seed("doc.md", "theirs", "v2")
	manifest := NewManifest()
	manifest.Record("/workspace", "doc.md", MountEntry{Key: "doc.md", Size: 10, Version: "v1"})

	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/doc.md", "mine")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewStatHashDetector()))

	runTool(t, tools, "shell", `{"command":"edit"}`) // rejected, manifest adopts v2

	mount.seed("doc.md", "a third writer", "v3") // lands before the retry

	note := decodeContent(t, runTool(t, tools, "shell", `{"command":"try again"}`))
	if !strings.Contains(note, "workspace commit failed") {
		t.Fatalf("the retry was not rejected; adopting a version must not disarm the precondition:\n%s", note)
	}
	if got := string(mount.entries["doc.md"].data); got != "a third writer" {
		t.Fatalf("backend doc.md = %q, want the third writer's content intact", got)
	}
}

// ── what a rejection tells the model ──
//
// The rejection is not the feature; the message is. These pin the parts of it
// a model has to be able to act on: which file, what it says now, changed
// versus deleted, and an instruction to re-read before writing again — all of
// it bounded, and none of it at the cost of the tool call's own status.

// conflictOn wires a workspace whose backend has already moved on: the
// manifest believes every key is at v1, the backend holds `stored` at v2, and
// the guest is about to write `local` over it. That is a rejected commit.
func conflictOn(t *testing.T, files map[string]string, local map[string]string) (*txFakeMount, oasis.ToolResult) {
	t.Helper()
	mount := newTxFakeMount()
	manifest := NewManifest()
	for key, body := range files {
		mount.seed(key, body, "v2")
		manifest.Record("/workspace", key, MountEntry{Key: key, Size: int64(len(body)), Version: "v1"})
	}
	sb := newCommitSandbox(func(s *recordingSandbox) {
		for key, body := range local {
			writeGuestFile(s, "/workspace/"+key, body)
		}
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewFullScanDetector()))
	return mount, runTool(t, tools, "shell", `{"command":"edit"}`)
}

// requireSuccessfulToolCall is the invariant every case below shares: a
// rejected commit explains itself inside a result that is still a success. A
// model told its shell call failed re-runs it, and re-running a build or a
// migration is worse than a failed save.
func requireSuccessfulToolCall(t *testing.T, res oasis.ToolResult) string {
	t.Helper()
	if res.Error != "" {
		t.Fatalf("a failed commit turned a successful tool call into an error: %q", res.Error)
	}
	note := decodeContent(t, res)
	if !strings.Contains(note, "ran edit") {
		t.Fatalf("the tool's own output was lost: %q", note)
	}
	return note
}

func TestConflictNoteCarriesTheCurrentContentAndTellsTheModelToReread(t *testing.T) {
	_, res := conflictOn(t,
		map[string]string{"doc.md": "# Report\n\ntheir paragraph\n"},
		map[string]string{"doc.md": "# Report\n\nmy paragraph\n"})
	note := requireSuccessfulToolCall(t, res)

	for _, want := range []string{
		"/workspace/doc.md",            // the path the model knows the file by, not the mount key
		"CHANGED",                      // what happened
		"their paragraph",              // what the file says now — the whole point
		"re-read",                      // what to do about it
		"nothing was saved",            // the write did not half-land
		"your own uncommitted version", // which copy is which
	} {
		if !strings.Contains(note, want) {
			t.Errorf("conflict note is missing %q:\n%s", want, note)
		}
	}
	if strings.Contains(note, "my paragraph") {
		t.Errorf("the note echoed the model's own write back at it instead of the stored content:\n%s", note)
	}
}

func TestDeletedKeyReadsDifferentlyFromAChangedOne(t *testing.T) {
	// Deleted: the manifest believes v1, the backend has nothing at all.
	mount := newTxFakeMount()
	manifest := NewManifest()
	manifest.Record("/workspace", "doc.md", MountEntry{Key: "doc.md", Size: 6, Version: "v1"})
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/doc.md", "my longer rewrite")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewFullScanDetector()))
	deleted := requireSuccessfulToolCall(t, runTool(t, tools, "shell", `{"command":"edit"}`))

	_, changedRes := conflictOn(t, map[string]string{"doc.md": "theirs"}, map[string]string{"doc.md": "mine"})
	changed := requireSuccessfulToolCall(t, changedRes)

	if !strings.Contains(deleted, "DELETED") {
		t.Errorf("a deleted key was not reported as deleted:\n%s", deleted)
	}
	if strings.Contains(deleted, "CHANGED") {
		t.Errorf("a deleted key was reported as a change; recreating it is a decision, not a merge:\n%s", deleted)
	}
	if !strings.Contains(deleted, "Do not recreate it") {
		t.Errorf("the note does not tell the model to decide rather than blindly recreate:\n%s", deleted)
	}
	if strings.Contains(deleted, "--- BEGIN") {
		t.Errorf("a deleted key came with content to merge against:\n%s", deleted)
	}
	if deleted == changed {
		t.Error("a deleted key and a changed key produced the same message")
	}
	if !strings.Contains(changed, "--- BEGIN /workspace/doc.md ---") || !strings.Contains(changed, "theirs") {
		t.Errorf("a changed key came without the content to merge against:\n%s", changed)
	}
}

func TestTakenNameIsNotReportedAsAChange(t *testing.T) {
	// The framework claims a name nobody has (ExpectAbsent on a prefetched
	// mount) and somebody does.
	mount := newTxFakeMount()
	mount.seed("report.md", "someone got here first", "v7")
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/report.md", "mine")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))
	note := requireSuccessfulToolCall(t, runTool(t, tools, "shell", `{"command":"edit"}`))

	if !strings.Contains(note, "ALREADY EXISTS") {
		t.Errorf("a taken name was not reported as one:\n%s", note)
	}
	if !strings.Contains(note, "someone got here first") {
		t.Errorf("the note did not show what is under the name already:\n%s", note)
	}
	if !strings.Contains(note, "choose another name") {
		t.Errorf("the note did not offer the action a taken name calls for:\n%s", note)
	}
}

func TestBinaryConflictPointsAtRereadingRatherThanInliningBytes(t *testing.T) {
	// An .xlsx is a zip: a PK header, then NUL bytes for pages.
	xlsx := "PK\x03\x04\x14\x00\x00\x00\x08\x00" + strings.Repeat("\x00\xff\xfe", 400)
	_, res := conflictOn(t,
		map[string]string{"book.xlsx": xlsx},
		map[string]string{"book.xlsx": "PK\x03\x04 my rewritten workbook"})
	note := requireSuccessfulToolCall(t, res)

	if strings.Contains(note, "\x00") {
		t.Errorf("binary content was dumped into the model's context:\n%q", note)
	}
	if !strings.Contains(note, "binary") || !strings.Contains(note, "re-read the file with a file tool") {
		t.Errorf("the note did not redirect the model to reading the file itself:\n%s", note)
	}
	if !strings.Contains(note, "/workspace/book.xlsx") || !strings.Contains(note, "CHANGED") {
		t.Errorf("dropping the content also dropped the conflict:\n%s", note)
	}
}

func TestOversizedTextConflictIsCutAndSaysSo(t *testing.T) {
	stored := strings.Repeat("stored line that nobody wants all of\n", 4000) // ~140 KB
	_, res := conflictOn(t,
		map[string]string{"log.txt": stored},
		map[string]string{"log.txt": "my line\n"})
	note := requireSuccessfulToolCall(t, res)

	if len(note) > 8*1024 {
		t.Errorf("conflict note is %d bytes for one %s file; the bound is %d bytes of content",
			len(note), humanSize(int64(len(stored))), maxConflictContentBytes)
	}
	if !strings.Contains(note, "truncated") || !strings.Contains(note, "the stored file is longer") {
		t.Errorf("the cut was silent; the model would treat a prefix as the whole file:\n%s", note)
	}
	if !strings.Contains(note, "stored line that nobody wants all of") {
		t.Errorf("the head of the file was not shown at all:\n%s", note)
	}
}

func TestManyKeyConflictIsSummarisedWithinTheBound(t *testing.T) {
	stored := make(map[string]string, 25)
	local := make(map[string]string, 25)
	for i := range 25 {
		key := fmt.Sprintf("f%02d.md", i)
		stored[key] = "theirs " + key
		local[key] = "mine " + key
	}
	_, res := conflictOn(t, stored, local)
	note := requireSuccessfulToolCall(t, res)

	if !strings.Contains(note, "25 of the files") {
		t.Errorf("the note does not report how many files were rejected:\n%s", note)
	}
	if !strings.Contains(note, "And 15 more files were rejected") {
		t.Errorf("the note is not summarised past %d named files:\n%s", maxConflictFilesNamed, note)
	}
	// Content for three, names for ten, a count for the rest.
	if got := strings.Count(note, "--- BEGIN "); got != maxConflictFilesDetailed {
		t.Errorf("note inlined content for %d files, want %d", got, maxConflictFilesDetailed)
	}
	if len(note) > 8*1024 {
		t.Errorf("a 25-file conflict produced a %d-byte note; a commit can carry a whole workspace", len(note))
	}
}

// blindMount rejects the commit and then cannot serve the readback either —
// the backend is reachable enough to say no and not enough to say what it
// holds.
type blindMount struct{ *txFakeMount }

func (m *blindMount) Open(ctx context.Context, key string) (io.ReadCloser, error) {
	return nil, errors.New("backend read timed out")
}

func TestUnreadableCurrentContentStillNamesTheConflict(t *testing.T) {
	mount := &blindMount{txFakeMount: newTxFakeMount()}
	mount.seed("doc.md", "theirs", "v2")
	manifest := NewManifest()
	manifest.Record("/workspace", "doc.md", MountEntry{Key: "doc.md", Size: 6, Version: "v1"})
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/doc.md", "mine")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewFullScanDetector()))
	note := requireSuccessfulToolCall(t, runTool(t, tools, "shell", `{"command":"edit"}`))

	if !strings.Contains(note, "/workspace/doc.md") || !strings.Contains(note, "CHANGED") {
		t.Errorf("a failed readback lost the conflict itself:\n%s", note)
	}
	if !strings.Contains(note, "backend read timed out") {
		t.Errorf("the note does not say why the content is missing:\n%s", note)
	}
	if !strings.Contains(note, "re-read") {
		t.Errorf("the note dropped the instruction along with the content:\n%s", note)
	}
}

// deadMount cannot commit at all — nothing to do with a second writer.
type deadMount struct{ *txFakeMount }

func (m *deadMount) Commit(ctx context.Context, changes []MountChange) (CommitResult, error) {
	return CommitResult{}, errors.New("backend unavailable")
}

func TestNonConflictCommitFailureIsADifferentMessageWithNoReread(t *testing.T) {
	mount := &deadMount{txFakeMount: newTxFakeMount()}
	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/doc.md", "mine")
	})
	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))
	note := requireSuccessfulToolCall(t, runTool(t, tools, "shell", `{"command":"edit"}`))

	if !strings.Contains(note, "backend unavailable") {
		t.Errorf("the failure was not surfaced:\n%s", note)
	}
	for _, unwanted := range []string{"in storage by another writer", "What to do next", "CHANGED", "--- BEGIN"} {
		if strings.Contains(note, unwanted) {
			t.Errorf("a storage failure was dressed up as a conflict (%q):\n%s", unwanted, note)
		}
	}
	if !strings.Contains(note, "do not re-run it") {
		t.Errorf("the note does not stop the model re-running the command:\n%s", note)
	}
	if !strings.Contains(note, "nothing to re-read") {
		t.Errorf("the note does not say there is nothing for the model to fix:\n%s", note)
	}
}

func TestUnrelatedSweepErrorsRideAlongWithoutBuryingTheConflict(t *testing.T) {
	mount := newTxFakeMount()
	mount.seed("doc.md", "theirs", "v2")
	manifest := NewManifest()
	manifest.Record("/workspace", "doc.md", MountEntry{Key: "doc.md", Size: 6, Version: "v1"})

	sb := newUnreadableSandbox("/workspace/scratch.bin")
	writeGuestFile(sb.recordingSandbox, "/workspace/doc.md", "mine")
	writeGuestFile(sb.recordingSandbox, "/workspace/scratch.bin", "vanishing")

	tools := Tools(sb, WithMounts(workspaceSpec(mount), manifest), WithToolCallCommits(NewFullScanDetector()))
	note := requireSuccessfulToolCall(t, runTool(t, tools, "shell", `{"command":"edit"}`))

	if !strings.Contains(note, "in storage by another writer") || !strings.Contains(note, "theirs") {
		t.Errorf("the conflict was buried by an unrelated error:\n%s", note)
	}
	if !strings.Contains(note, "scratch.bin") || !strings.Contains(note, "not conflicts") {
		t.Errorf("the unrelated error was dropped instead of being labelled as unrelated:\n%s", note)
	}
}

// ── seeding from prefetch ──

func TestFirstCommitDoesNotRepublishThePrefetchedWorkspace(t *testing.T) {
	mount := newTxFakeMount()
	mount.seed("doc.md", "prefetched", "v1")
	mount.seed("data.csv", "id,value", "v1")

	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/new.md", "written by shell")
	})
	specs := workspaceSpec(mount)
	manifest := NewManifest()
	if err := PrefetchMounts(context.Background(), sb.recordingSandbox, specs, manifest); err != nil {
		t.Fatalf("PrefetchMounts: %v", err)
	}
	tools := Tools(sb, WithMounts(specs, manifest), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "shell", `{"command":"write new.md"}`)

	if len(mount.commits) != 1 {
		t.Fatalf("backend saw %d commits, want 1", len(mount.commits))
	}
	if got := len(mount.commits[0]); got != 1 {
		t.Fatalf("commit carried %d changes, want only the new file — prefetched files must not be committed back", got)
	}
	if mount.commits[0][0].Key != "new.md" {
		t.Errorf("committed key = %q, want new.md", mount.commits[0][0].Key)
	}
	for _, key := range []string{"doc.md", "data.csv"} {
		if got := mount.entries[key].version; got != "v1" {
			t.Errorf("%s version = %q, want v1 — an untouched prefetched file must not gain a version", key, got)
		}
	}
}

func TestPrefetchedFileEditedByShellIsCommitted(t *testing.T) {
	mount := newTxFakeMount()
	mount.seed("doc.md", "prefetched", "v1")

	sb := newCommitSandbox(func(s *recordingSandbox) {
		writeGuestFile(s, "/workspace/doc.md", "rewritten by shell, a different length")
	})
	specs := workspaceSpec(mount)
	manifest := NewManifest()
	if err := PrefetchMounts(context.Background(), sb.recordingSandbox, specs, manifest); err != nil {
		t.Fatalf("PrefetchMounts: %v", err)
	}
	tools := Tools(sb, WithMounts(specs, manifest), WithToolCallCommits(NewFullScanDetector()))

	runTool(t, tools, "shell", `{"command":"sed -i ..."}`)

	if got := string(mount.entries["doc.md"].data); got != "rewritten by shell, a different length" {
		t.Errorf("backend doc.md = %q, want the shell edit", got)
	}
	if got := mount.commits[0][0].Have; got != "v1" {
		t.Errorf("precondition asserted %q, want the prefetched version v1", got)
	}
}

// ── the precondition rule, per mount kind ──

func TestCommitPreconditionPerMountKind(t *testing.T) {
	prefetched := &MountSpec{Path: "/workspace", Mode: MountReadWrite, PrefetchOnStart: true}
	readThrough := &MountSpec{Path: "/workspace/inputs", Mode: MountReadWrite} // never prefetched
	writeOnly := &MountSpec{Path: "/out", Mode: MountWriteOnly}

	tracked := NewManifest()
	tracked.Record("/workspace", "doc.md", MountEntry{Key: "doc.md", Version: "v3"})
	tracked.Record("/workspace", "novers.md", MountEntry{Key: "novers.md"})

	cases := []struct {
		name     string
		manifest *Manifest
		spec     *MountSpec
		key      string
		expect   VersionExpectation
		have     string
	}{
		{"tracked key asserts its version", tracked, prefetched, "doc.md", ExpectVersion, "v3"},
		{"tracked with no version cannot assert one", tracked, prefetched, "novers.md", ExpectAny, ""},
		{"new file on a prefetched mount claims the name", tracked, prefetched, "fresh.md", ExpectAbsent, ""},
		{"never-prefetched mount knows nothing", tracked, readThrough, "fresh.md", ExpectAny, ""},
		{"write-only mount knows nothing", tracked, writeOnly, "fresh.md", ExpectAny, ""},
		{"no manifest at all", nil, prefetched, "doc.md", ExpectAbsent, ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			expect, have := commitPrecondition(c.manifest, c.spec, c.key)
			if expect != c.expect || have != c.have {
				t.Errorf("commitPrecondition = (%v, %q), want (%v, %q)", expect, have, c.expect, c.have)
			}
		})
	}
}

// ── the detector's own seam ──

func TestFullScanDetectorTrustsAContentAddressedVersion(t *testing.T) {
	// A backend that addresses content by its hash reports that hash as the
	// version, which makes the first-scan comparison exact rather than a size
	// guess — the case the workspace backend is moving to.
	body := "the very same bytes"
	sb := newRecordingSandbox()
	sb.files["/workspace/doc.md"] = []byte(body)

	d := NewFullScanDetector()
	changed, err := d.Scan(context.Background(), sb, ChangeScan{
		Root: "/workspace",
		Baseline: func(string) (MountEntry, bool) {
			// Deliberately the wrong size: only the digest should decide.
			return MountEntry{Version: contentDigest([]byte(body)), Size: 999}, true
		},
	})
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(changed) != 0 {
		t.Errorf("Scan reported %d changes, want 0 — the backend already holds this content", len(changed))
	}
}

func TestFullScanDetectorReportsAgainUntilCommitted(t *testing.T) {
	sb := newRecordingSandbox()
	sb.files["/workspace/doc.md"] = []byte("hello")

	d := NewFullScanDetector()
	scan := ChangeScan{Root: "/workspace"}

	first, err := d.Scan(context.Background(), sb, scan)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(first) != 1 {
		t.Fatalf("first scan reported %d changes, want 1", len(first))
	}
	again, _ := d.Scan(context.Background(), sb, scan)
	if len(again) != 1 {
		t.Fatalf("second scan reported %d changes, want 1 — nothing said the commit landed", len(again))
	}
	d.Committed(first)
	after, _ := d.Scan(context.Background(), sb, scan)
	if len(after) != 0 {
		t.Errorf("scan after Committed reported %d changes, want 0", len(after))
	}
}

// unreadableSandbox lists a file the read cannot serve — a temp file the
// command that just ran removed between the enumeration and the fetch.
type unreadableSandbox struct {
	*commitSandbox
	gone string
}

func newUnreadableSandbox(gone string) *unreadableSandbox {
	return &unreadableSandbox{commitSandbox: newCommitSandbox(nil), gone: gone}
}

func (s *unreadableSandbox) DownloadFile(ctx context.Context, path string) (io.ReadCloser, error) {
	if path == s.gone {
		return nil, errors.New("no such file")
	}
	return s.commitSandbox.DownloadFile(ctx, path)
}

func TestFullScanDetectorReportsWhatItCouldReadAndSaysWhatItCouldNot(t *testing.T) {
	sb := newUnreadableSandbox("/workspace/gone.tmp")
	writeGuestFile(sb.recordingSandbox, "/workspace/good.md", "readable")
	writeGuestFile(sb.recordingSandbox, "/workspace/gone.tmp", "about to vanish")

	changed, err := NewFullScanDetector().Scan(context.Background(), sb, ChangeScan{Root: "/workspace"})
	if err == nil {
		t.Error("Scan swallowed an unreadable file; the caller has no way to know its scan was partial")
	}
	if len(changed) != 1 || changed[0].Path != "/workspace/good.md" {
		t.Fatalf("Scan reported %+v, want the one file it could read — an unreadable temp file must not block the workspace", changed)
	}
}

func TestOneUnreadableFileDoesNotStopTheCommit(t *testing.T) {
	mount := newTxFakeMount()
	sb := newUnreadableSandbox("/workspace/scratch.bin")
	writeGuestFile(sb.recordingSandbox, "/workspace/report.md", "the deliverable")
	writeGuestFile(sb.recordingSandbox, "/workspace/scratch.bin", "vanishing")

	tools := Tools(sb, WithMounts(workspaceSpec(mount), NewManifest()), WithToolCallCommits(NewFullScanDetector()))
	res := runTool(t, tools, "mcp_call", `{"server":"tex","tool":"build"}`)

	if got := string(mount.entries["report.md"].data); got != "the deliverable" {
		t.Errorf("backend report.md = %q, want the file that could be read", got)
	}
	if !strings.Contains(decodeContent(t, res), "workspace commit failed") {
		t.Errorf("the unreadable file was not reported anywhere: %q", decodeContent(t, res))
	}
}
